version: '3'
services:
  rbc:
    build: ./rbc
    ports:
      - "8081:8080"
    depends_on:
      - dbpostgresql
  weather:
    build: ./weather
    ports:
      - "8082:8080"
  predict:
    build: ./predict
    ports:
      - "8083:8080"
  dbpostgresql:
    image: postgres
    restart: always
    ports:
      - "8090:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: adminadmin
      POSTGRES_PASSWORD: pwdpwd
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
